Neos:
  Flow:
    mvc:
      routes:
        'PunktDe.Form.Persistence':
          position: start

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'PunktDe.Form.Persistence':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'PunktDe\Form\Persistence\Controller\.*'

  Neos:
    fusion:
      autoInclude:
        'PunktDe.Form.Persistence': true
    modules:
      management:
        submodules:
          formDataDownload:
            label: 'Form Data Download'
            controller: 'PunktDe\Form\Persistence\Controller\Backend\FormDataController'
            description: 'Download saved form data for the forms on this site'
            icon: 'fas fa-file-download'
            privilegeTarget: 'PunktDe.Form.Persistence:DownLoadFormData'
    userInterface:
      translation:
        autoInclude:
          'PunktDe.Form.Persistence':
            - 'Modules/*'
  Fusion:
    defaultContext:
      PunktDe.FormExport.ExportDefinition: 'PunktDe\Form\Persistence\Fusion\Eel\ExportDefinitionHelper'

  Form:
    presets:
      'default':
        finisherPresets:
          'PunktDe.Form.Persistence:SaveFormDataFinisher':
            implementationClassName: PunktDe\Form\Persistence\Finishers\SaveFormDataFinisher
            options: {  }

    FusionRenderer:
      fusionAutoInclude:
        'PunktDe.Form.Persistence': true

