PunktDe:
  Form:
    Persistence:
      exportDefinitions:
        csv:
          label: Generic CSV
          exporter: csv
          fileNamePattern: "Form-Export-{formIdentifier}-{currentDate}.csv"

      exporter:
        csv:
          className: PunktDe\Form\Persistence\Domain\Exporter\CsvExporter
          options: []
