Neos:
  Neos:
    fusion:
      autoInclude:
        'PunktDe.Form.Persistence': true
    modules:
      administration:
        submodules:
          formDataDownload:
            label: 'Form Data Download'
            controller: 'PunktDe\Form\Persistence\Controller\Backend\FormDataController'
            description: 'Download saved form data for the forms on this site'
            icon: 'fas fa-file-download'
            privilegeTarget: 'PunktDe.Form.Persistence:DownLoadFormData'

  Form:
    presets:
      'default':
        finisherPresets:
          'PunktDe.Form.Persistence:SaveFormDataFinisher':
            implementationClassName: PunktDe\Form\Persistence\Finishers\SaveFormDataFinisher
            options: {  }

    FusionRenderer:
      fusionAutoInclude:
        'PunktDe.Form.Persistence': true
